config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :games
  get 'index', to: 'static_pages#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#show'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :games
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  skip_before_action :verify_authenticity_token, only: [ :update, :destroy ]
  before_action :authenticate_user!

  def index
    games = Game.all
    render json: games.as_json()
  end

  def new
    @game = Game.new
  end

  def show
    game = Game.find(params[:id])
    render json: game.as_json()
  end

  def create
    @game = current_user.games.create()
    @game.update_attribute(:player_1, @game.user.email)
    redirect_to edit_game_path(@game)
  end

  def edit
    @game = Game.find(params[:id])
    if @game.player_1 != current_user.email && @game.player_2 == ''
      @game.update_attribute(:player_2, current_user.email)
    end
    if current_user.email != @game.player_1 && current_user.email != @game.player_2
      redirect_to games_path, alert: "Game is full, sorry"
    end
  end

  def update
    game = Game.find(params[:id])
    game.update_attribute(:board, board_param["board"])
    game.update_attribute(:black_teams_turn, !game.black_teams_turn)
    render json: game.as_json()
  end

  def destroy
    game = Game.find_by_id(params[:id])
    redirect_to index_path
    game.destroy if game
  end

  private

  def board_param
    params.require(:game)
  end

end
  

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :authenticate_user!, only: [ :index ]

  def index
  end

  def show
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/games/edit.html.erb
<div class="in-game-lobby-link">
  <%= link_to 'End match and return to game lobby', game_path(@game), method: :delete, class: 'btn btn-primary make-it-green' %>
  <br /><br />
</div>

<% player = "player_1" %>
<% if @game.user != current_user %>
  <% player = "player_2" %>
<% end %>

<div class="container game box">
  <%= react_component("Game", {id: @game.id, player: player}) %>
</div>

app/views/games/new.html.erb
<div class="text-center">
  <div class="container">
    <div class="make-it-green are-you-sure-box col-10">
      <%= simple_form_for @game do |f| %>
        <%= f.submit 'Are you sure?', class: 'btn btn-primary make-it-green' %>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Chess</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <div id="flex-content-container">
      <nav class="navbar fixed-top navbar-toggleable-md header-color">
        <div id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
          <span> 
            <div class="nav-item">
              <div class="homepage_link">
                <%= link_to 'Go to Homepage', root_path %>
              </div>
              <br/>
              </span>
            </div>
          </ul>
        </div>
      </nav>
    <br/><br/><br/><br/>

    <div class="make-it-green text-center">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    </div>

    <%= yield %>
    </div>
  
    <div id="footer">
      <div class="text-center">
        <a class="fa fa-github-square fa-3x make-it-green" href="https://github.com/Learningstuff98/rails-chess-app"></a>
        <span class="linkedin">
          <a class="fa fa-linkedin-square fa-3x make-it-green" href="https://www.linkedin.com/in/andy-strube-6231ba152/"></a>
        </span>
        <span class="resume">
          <a class="fa fa-file-text fa-3x make-it-green" href="https://docs.google.com/document/d/1qm4nBdIZfsx8zh4IwYvkVuQYclpOXUCVxnC9vV3_eBM/edit"></a>
        </span>
      </div>
    </div>

  </body>
</html>

app/views/static_pages/index.html.erb
<div class="text-center">
  <div class="container">
    <div class="make-it-green box col-10">
      <%= link_to "Start a new game", new_game_path, class: 'btn btn-primary make-it-green' %>
      <br /><br />
      <h2>Pick a chess match to join</h2>
      <%= react_component("GamesList") %>
    </div>
  </div>
</div>

app/views/static_pages/show.html.erb
<div class="text-center">
  <div class="container">
    <div class="make-it-green box col-10">
      <h2>Multiplayer Chess App by Andy Strube</h2>
      <h3>Sign up or log in to start playing!</h3>
      <br/>

      <% if current_user %>
        <%= link_to "Start a new game", new_game_path, class: 'btn btn-primary make-it-green' %>
        <br /><br/>
        <%= link_to 'Go to games lobby', index_path, class: 'btn btn-primary make-it-green' %>
        <br/><br/>
        <%= link_to 'Log out', destroy_user_session_path, method: :delete, class: 'btn btn-primary make-it-green' %>
      <% end %>

      <% if !current_user %>
        <%= link_to 'Log in', new_user_session_path, class: 'btn btn-primary make-it-green' %>
        <br/><br/>
        <%= link_to 'Sign up', new_user_registration_path, class: 'btn btn-primary make-it-green' %>
        <br/><br/>
      <% end %>

    </div>
  </div>
</div>